/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FertilizerRarity = IDL.Variant({
  'epic' : IDL.Null,
  'legendary' : IDL.Null,
  'rare' : IDL.Null,
  'common' : IDL.Null,
});
export const Time = IDL.Int;
export const Fermentation = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'duration' : IDL.Nat,
  'player' : IDL.Principal,
  'soil' : IDL.Nat,
  'animalWaste' : IDL.Nat,
  'fertilizerId' : IDL.Nat,
  'water' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CropState = IDL.Variant({
  'empty' : IDL.Null,
  'planted' : IDL.Null,
  'growing' : IDL.Null,
  'readyToHarvest' : IDL.Null,
});
export const Plot = IDL.Record({
  'state' : CropState,
  'growthStartTime' : IDL.Opt(Time),
  'cropType' : IDL.Opt(IDL.Text),
  'index' : IDL.Nat,
  'fertilizerId' : IDL.Opt(IDL.Nat),
  'harvestTime' : IDL.Opt(Time),
});
export const Fertilizer = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'growthPower' : IDL.Nat,
  'microbeBoost' : IDL.Nat,
  'quantity' : IDL.Nat,
  'rarity' : FertilizerRarity,
  'soilStability' : IDL.Nat,
});
export const EvolutionTier = IDL.Record({
  'threshold' : IDL.Nat,
  'tier' : IDL.Nat,
  'unlockedTime' : IDL.Opt(Time),
});
export const EvolutionState = IDL.Record({
  'meter' : IDL.Nat,
  'tiers' : IDL.Vec(EvolutionTier),
  'lastEvolution' : Time,
  'currentTier' : IDL.Nat,
  'goalsReached' : IDL.Nat,
});
export const JackpotState = IDL.Record({
  'lastWinner' : IDL.Opt(IDL.Principal),
  'pool' : IDL.Nat,
  'lastClaim' : IDL.Opt(Time),
  'totalClaims' : IDL.Nat,
});
export const PlayerProfile = IDL.Record({
  'battlesLost' : IDL.Nat,
  'principal' : IDL.Principal,
  'evolutions' : IDL.Nat,
  'lastDailyReset' : Time,
  'plots' : IDL.Vec(Plot),
  'harvests' : IDL.Nat,
  'soilBalance' : IDL.Nat,
  'battlesWon' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyFertilizer' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimJackpot' : IDL.Func([IDL.Nat], [], []),
  'completeFermentation' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createFertilizer' : IDL.Func(
      [FertilizerRarity, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createPlayerProfile' : IDL.Func([], [], []),
  'getActiveFermentations' : IDL.Func([], [IDL.Vec(Fermentation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFarmPlots' : IDL.Func([], [IDL.Vec(Plot)], ['query']),
  'getFertilizerInventory' : IDL.Func([], [IDL.Vec(Fertilizer)], ['query']),
  'getGlobalEvolutionState' : IDL.Func([], [EvolutionState], ['query']),
  'getJackpotPool' : IDL.Func([], [JackpotState], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'harvestCrop' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'plantCrop' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'resetJackpot' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setEvolutionState' : IDL.Func([EvolutionState], [], []),
  'startFermentation' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FertilizerRarity = IDL.Variant({
    'epic' : IDL.Null,
    'legendary' : IDL.Null,
    'rare' : IDL.Null,
    'common' : IDL.Null,
  });
  const Time = IDL.Int;
  const Fermentation = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'duration' : IDL.Nat,
    'player' : IDL.Principal,
    'soil' : IDL.Nat,
    'animalWaste' : IDL.Nat,
    'fertilizerId' : IDL.Nat,
    'water' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CropState = IDL.Variant({
    'empty' : IDL.Null,
    'planted' : IDL.Null,
    'growing' : IDL.Null,
    'readyToHarvest' : IDL.Null,
  });
  const Plot = IDL.Record({
    'state' : CropState,
    'growthStartTime' : IDL.Opt(Time),
    'cropType' : IDL.Opt(IDL.Text),
    'index' : IDL.Nat,
    'fertilizerId' : IDL.Opt(IDL.Nat),
    'harvestTime' : IDL.Opt(Time),
  });
  const Fertilizer = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'growthPower' : IDL.Nat,
    'microbeBoost' : IDL.Nat,
    'quantity' : IDL.Nat,
    'rarity' : FertilizerRarity,
    'soilStability' : IDL.Nat,
  });
  const EvolutionTier = IDL.Record({
    'threshold' : IDL.Nat,
    'tier' : IDL.Nat,
    'unlockedTime' : IDL.Opt(Time),
  });
  const EvolutionState = IDL.Record({
    'meter' : IDL.Nat,
    'tiers' : IDL.Vec(EvolutionTier),
    'lastEvolution' : Time,
    'currentTier' : IDL.Nat,
    'goalsReached' : IDL.Nat,
  });
  const JackpotState = IDL.Record({
    'lastWinner' : IDL.Opt(IDL.Principal),
    'pool' : IDL.Nat,
    'lastClaim' : IDL.Opt(Time),
    'totalClaims' : IDL.Nat,
  });
  const PlayerProfile = IDL.Record({
    'battlesLost' : IDL.Nat,
    'principal' : IDL.Principal,
    'evolutions' : IDL.Nat,
    'lastDailyReset' : Time,
    'plots' : IDL.Vec(Plot),
    'harvests' : IDL.Nat,
    'soilBalance' : IDL.Nat,
    'battlesWon' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyFertilizer' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimJackpot' : IDL.Func([IDL.Nat], [], []),
    'completeFermentation' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createFertilizer' : IDL.Func(
        [FertilizerRarity, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createPlayerProfile' : IDL.Func([], [], []),
    'getActiveFermentations' : IDL.Func([], [IDL.Vec(Fermentation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFarmPlots' : IDL.Func([], [IDL.Vec(Plot)], ['query']),
    'getFertilizerInventory' : IDL.Func([], [IDL.Vec(Fertilizer)], ['query']),
    'getGlobalEvolutionState' : IDL.Func([], [EvolutionState], ['query']),
    'getJackpotPool' : IDL.Func([], [JackpotState], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'harvestCrop' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'plantCrop' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'resetJackpot' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setEvolutionState' : IDL.Func([EvolutionState], [], []),
    'startFermentation' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };