/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CropState = { 'empty' : null } |
  { 'planted' : null } |
  { 'growing' : null } |
  { 'readyToHarvest' : null };
export interface EvolutionState {
  'meter' : bigint,
  'tiers' : Array<EvolutionTier>,
  'lastEvolution' : Time,
  'currentTier' : bigint,
  'goalsReached' : bigint,
}
export interface EvolutionTier {
  'threshold' : bigint,
  'tier' : bigint,
  'unlockedTime' : [] | [Time],
}
export interface Fermentation {
  'id' : bigint,
  'startTime' : Time,
  'duration' : bigint,
  'player' : Principal,
  'soil' : bigint,
  'animalWaste' : bigint,
  'fertilizerId' : bigint,
  'water' : bigint,
}
export interface Fertilizer {
  'id' : bigint,
  'owner' : Principal,
  'growthPower' : bigint,
  'microbeBoost' : bigint,
  'quantity' : bigint,
  'rarity' : FertilizerRarity,
  'soilStability' : bigint,
}
export type FertilizerRarity = { 'epic' : null } |
  { 'legendary' : null } |
  { 'rare' : null } |
  { 'common' : null };
export interface JackpotState {
  'lastWinner' : [] | [Principal],
  'pool' : bigint,
  'lastClaim' : [] | [Time],
  'totalClaims' : bigint,
}
export interface PlayerProfile {
  'battlesLost' : bigint,
  'principal' : Principal,
  'evolutions' : bigint,
  'lastDailyReset' : Time,
  'plots' : Array<Plot>,
  'harvests' : bigint,
  'soilBalance' : bigint,
  'battlesWon' : bigint,
}
export interface Plot {
  'state' : CropState,
  'growthStartTime' : [] | [Time],
  'cropType' : [] | [string],
  'index' : bigint,
  'fertilizerId' : [] | [bigint],
  'harvestTime' : [] | [Time],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyFertilizer' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimJackpot' : ActorMethod<[bigint], undefined>,
  'completeFermentation' : ActorMethod<[bigint, bigint], undefined>,
  'createFertilizer' : ActorMethod<
    [FertilizerRarity, bigint, bigint, bigint],
    bigint
  >,
  'createPlayerProfile' : ActorMethod<[], undefined>,
  'getActiveFermentations' : ActorMethod<[], Array<Fermentation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFarmPlots' : ActorMethod<[], Array<Plot>>,
  'getFertilizerInventory' : ActorMethod<[], Array<Fertilizer>>,
  'getGlobalEvolutionState' : ActorMethod<[], EvolutionState>,
  'getJackpotPool' : ActorMethod<[], JackpotState>,
  'getLeaderboard' : ActorMethod<[], Array<PlayerProfile>>,
  'getPlayerProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'harvestCrop' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'plantCrop' : ActorMethod<[bigint, string], undefined>,
  'resetJackpot' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setEvolutionState' : ActorMethod<[EvolutionState], undefined>,
  'startFermentation' : ActorMethod<[bigint, bigint, bigint, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];