/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Fertilizer {
    id: bigint;
    owner: Principal;
    growthPower: bigint;
    microbeBoost: bigint;
    quantity: bigint;
    rarity: FertilizerRarity;
    soilStability: bigint;
}
export type Time = bigint;
export interface EvolutionTier {
    threshold: bigint;
    tier: bigint;
    unlockedTime?: Time;
}
export interface PlayerProfile {
    battlesLost: bigint;
    principal: Principal;
    evolutions: bigint;
    lastDailyReset: Time;
    plots: Array<Plot>;
    harvests: bigint;
    soilBalance: bigint;
    battlesWon: bigint;
}
export interface EvolutionState {
    meter: bigint;
    tiers: Array<EvolutionTier>;
    lastEvolution: Time;
    currentTier: bigint;
    goalsReached: bigint;
}
export interface Plot {
    state: CropState;
    growthStartTime?: Time;
    cropType?: string;
    index: bigint;
    fertilizerId?: bigint;
    harvestTime?: Time;
}
export interface JackpotState {
    lastWinner?: Principal;
    pool: bigint;
    lastClaim?: Time;
    totalClaims: bigint;
}
export interface Fermentation {
    id: bigint;
    startTime: Time;
    duration: bigint;
    player: Principal;
    soil: bigint;
    animalWaste: bigint;
    fertilizerId: bigint;
    water: bigint;
}
export interface UserProfile {
    name: string;
}
export enum CropState {
    empty = "empty",
    planted = "planted",
    growing = "growing",
    readyToHarvest = "readyToHarvest"
}
export enum FertilizerRarity {
    epic = "epic",
    legendary = "legendary",
    rare = "rare",
    common = "common"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyFertilizer(plotIndex: bigint, fertilizerId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimJackpot(amount: bigint): Promise<void>;
    completeFermentation(fermentationId: bigint, fertilizerId: bigint): Promise<void>;
    createFertilizer(rarity: FertilizerRarity, growthPower: bigint, soilStability: bigint, microbeBoost: bigint): Promise<bigint>;
    createPlayerProfile(): Promise<void>;
    getActiveFermentations(): Promise<Array<Fermentation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFarmPlots(): Promise<Array<Plot>>;
    getFertilizerInventory(): Promise<Array<Fertilizer>>;
    getGlobalEvolutionState(): Promise<EvolutionState>;
    getJackpotPool(): Promise<JackpotState>;
    getLeaderboard(): Promise<Array<PlayerProfile>>;
    getPlayerProfile(): Promise<PlayerProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    harvestCrop(plotIndex: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    plantCrop(plotIndex: bigint, cropType: string): Promise<void>;
    resetJackpot(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setEvolutionState(newState: EvolutionState): Promise<void>;
    startFermentation(animalWaste: bigint, soil: bigint, water: bigint, duration: bigint): Promise<bigint>;
}
import type { CropState as _CropState, EvolutionState as _EvolutionState, EvolutionTier as _EvolutionTier, Fertilizer as _Fertilizer, FertilizerRarity as _FertilizerRarity, JackpotState as _JackpotState, PlayerProfile as _PlayerProfile, Plot as _Plot, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyFertilizer(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyFertilizer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyFertilizer(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimJackpot(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimJackpot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimJackpot(arg0);
            return result;
        }
    }
    async completeFermentation(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeFermentation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeFermentation(arg0, arg1);
            return result;
        }
    }
    async createFertilizer(arg0: FertilizerRarity, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFertilizer(to_candid_FertilizerRarity_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFertilizer(to_candid_FertilizerRarity_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async createPlayerProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayerProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayerProfile();
            return result;
        }
    }
    async getActiveFermentations(): Promise<Array<Fermentation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveFermentations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveFermentations();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmPlots(): Promise<Array<Plot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmPlots();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmPlots();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFertilizerInventory(): Promise<Array<Fertilizer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFertilizerInventory();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFertilizerInventory();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalEvolutionState(): Promise<EvolutionState> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalEvolutionState();
                return from_candid_EvolutionState_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalEvolutionState();
            return from_candid_EvolutionState_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJackpotPool(): Promise<JackpotState> {
        if (this.processError) {
            try {
                const result = await this.actor.getJackpotPool();
                return from_candid_JackpotState_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJackpotPool();
            return from_candid_JackpotState_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerProfile(): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async harvestCrop(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.harvestCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.harvestCrop(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async plantCrop(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.plantCrop(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.plantCrop(arg0, arg1);
            return result;
        }
    }
    async resetJackpot(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetJackpot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetJackpot();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setEvolutionState(arg0: EvolutionState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEvolutionState(to_candid_EvolutionState_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEvolutionState(to_candid_EvolutionState_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startFermentation(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startFermentation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startFermentation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_CropState_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropState): CropState {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_EvolutionState_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvolutionState): EvolutionState {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_EvolutionTier_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvolutionTier): EvolutionTier {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_FertilizerRarity_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FertilizerRarity): FertilizerRarity {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Fertilizer_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fertilizer): Fertilizer {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_JackpotState_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JackpotState): JackpotState {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfile): PlayerProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Plot_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Plot): Plot {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfile]): PlayerProfile | null {
    return value.length === 0 ? null : from_candid_PlayerProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    state: _CropState;
    growthStartTime: [] | [_Time];
    cropType: [] | [string];
    index: bigint;
    fertilizerId: [] | [bigint];
    harvestTime: [] | [_Time];
}): {
    state: CropState;
    growthStartTime?: Time;
    cropType?: string;
    index: bigint;
    fertilizerId?: bigint;
    harvestTime?: Time;
} {
    return {
        state: from_candid_CropState_n11(_uploadFile, _downloadFile, value.state),
        growthStartTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.growthStartTime)),
        cropType: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.cropType)),
        index: value.index,
        fertilizerId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.fertilizerId)),
        harvestTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.harvestTime))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: Principal;
    growthPower: bigint;
    microbeBoost: bigint;
    quantity: bigint;
    rarity: _FertilizerRarity;
    soilStability: bigint;
}): {
    id: bigint;
    owner: Principal;
    growthPower: bigint;
    microbeBoost: bigint;
    quantity: bigint;
    rarity: FertilizerRarity;
    soilStability: bigint;
} {
    return {
        id: value.id,
        owner: value.owner,
        growthPower: value.growthPower,
        microbeBoost: value.microbeBoost,
        quantity: value.quantity,
        rarity: from_candid_FertilizerRarity_n19(_uploadFile, _downloadFile, value.rarity),
        soilStability: value.soilStability
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meter: bigint;
    tiers: Array<_EvolutionTier>;
    lastEvolution: _Time;
    currentTier: bigint;
    goalsReached: bigint;
}): {
    meter: bigint;
    tiers: Array<EvolutionTier>;
    lastEvolution: Time;
    currentTier: bigint;
    goalsReached: bigint;
} {
    return {
        meter: value.meter,
        tiers: from_candid_vec_n23(_uploadFile, _downloadFile, value.tiers),
        lastEvolution: value.lastEvolution,
        currentTier: value.currentTier,
        goalsReached: value.goalsReached
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    threshold: bigint;
    tier: bigint;
    unlockedTime: [] | [_Time];
}): {
    threshold: bigint;
    tier: bigint;
    unlockedTime?: Time;
} {
    return {
        threshold: value.threshold,
        tier: value.tier,
        unlockedTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.unlockedTime))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastWinner: [] | [Principal];
    pool: bigint;
    lastClaim: [] | [_Time];
    totalClaims: bigint;
}): {
    lastWinner?: Principal;
    pool: bigint;
    lastClaim?: Time;
    totalClaims: bigint;
} {
    return {
        lastWinner: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.lastWinner)),
        pool: value.pool,
        lastClaim: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastClaim)),
        totalClaims: value.totalClaims
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    battlesLost: bigint;
    principal: Principal;
    evolutions: bigint;
    lastDailyReset: _Time;
    plots: Array<_Plot>;
    harvests: bigint;
    soilBalance: bigint;
    battlesWon: bigint;
}): {
    battlesLost: bigint;
    principal: Principal;
    evolutions: bigint;
    lastDailyReset: Time;
    plots: Array<Plot>;
    harvests: bigint;
    soilBalance: bigint;
    battlesWon: bigint;
} {
    return {
        battlesLost: value.battlesLost,
        principal: value.principal,
        evolutions: value.evolutions,
        lastDailyReset: value.lastDailyReset,
        plots: from_candid_vec_n8(_uploadFile, _downloadFile, value.plots),
        harvests: value.harvests,
        soilBalance: value.soilBalance,
        battlesWon: value.battlesWon
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    empty: null;
} | {
    planted: null;
} | {
    growing: null;
} | {
    readyToHarvest: null;
}): CropState {
    return "empty" in value ? CropState.empty : "planted" in value ? CropState.planted : "growing" in value ? CropState.growing : "readyToHarvest" in value ? CropState.readyToHarvest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    epic: null;
} | {
    legendary: null;
} | {
    rare: null;
} | {
    common: null;
}): FertilizerRarity {
    return "epic" in value ? FertilizerRarity.epic : "legendary" in value ? FertilizerRarity.legendary : "rare" in value ? FertilizerRarity.rare : "common" in value ? FertilizerRarity.common : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fertilizer>): Array<Fertilizer> {
    return value.map((x)=>from_candid_Fertilizer_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EvolutionTier>): Array<EvolutionTier> {
    return value.map((x)=>from_candid_EvolutionTier_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerProfile>): Array<PlayerProfile> {
    return value.map((x)=>from_candid_PlayerProfile_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Plot>): Array<Plot> {
    return value.map((x)=>from_candid_Plot_n9(_uploadFile, _downloadFile, x));
}
function to_candid_EvolutionState_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvolutionState): _EvolutionState {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_EvolutionTier_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvolutionTier): _EvolutionTier {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_FertilizerRarity_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FertilizerRarity): _FertilizerRarity {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meter: bigint;
    tiers: Array<EvolutionTier>;
    lastEvolution: Time;
    currentTier: bigint;
    goalsReached: bigint;
}): {
    meter: bigint;
    tiers: Array<_EvolutionTier>;
    lastEvolution: _Time;
    currentTier: bigint;
    goalsReached: bigint;
} {
    return {
        meter: value.meter,
        tiers: to_candid_vec_n35(_uploadFile, _downloadFile, value.tiers),
        lastEvolution: value.lastEvolution,
        currentTier: value.currentTier,
        goalsReached: value.goalsReached
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    threshold: bigint;
    tier: bigint;
    unlockedTime?: Time;
}): {
    threshold: bigint;
    tier: bigint;
    unlockedTime: [] | [_Time];
} {
    return {
        threshold: value.threshold,
        tier: value.tier,
        unlockedTime: value.unlockedTime ? candid_some(value.unlockedTime) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FertilizerRarity): {
    epic: null;
} | {
    legendary: null;
} | {
    rare: null;
} | {
    common: null;
} {
    return value == FertilizerRarity.epic ? {
        epic: null
    } : value == FertilizerRarity.legendary ? {
        legendary: null
    } : value == FertilizerRarity.rare ? {
        rare: null
    } : value == FertilizerRarity.common ? {
        common: null
    } : value;
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EvolutionTier>): Array<_EvolutionTier> {
    return value.map((x)=>to_candid_EvolutionTier_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
